#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# https://typicode.github.io/husky/#/?id=custom-directory
cd frontend
# https://github.com/okonet/lint-staged#command-line-flags
pnpm exec lint-staged --config .lintstagedrc.mjs
