services:
  nginx:
    profiles: ['backend']
    environment:
      ROOT_DIR: ${CONTAINER_PROJECT_DIR}/backend/public
    volumes:
      # cf. https://docs.docker.com/compose/compose-file/05-services/#long-syntax-5
      # cf. https://hub.docker.com/_/nginx - Using environment variables
      - type: bind
        source: ./backend/docker/nginx/default.conf
        target: /etc/nginx/templates/default.conf.template
        read_only: true
      - type: bind
        source: ./backend/docker/nginx/${ENV}.conf
        target: /etc/nginx/templates/${ENV}.conf.template
        read_only: true
      - type: bind
        source: ./backend/public
        target: ${CONTAINER_PROJECT_DIR}/backend/public
        read_only: true
    depends_on:
      php-fpm:
        condition: service_started
