# cf. https://docs.docker.com/compose/compose-file
# cf. https://docs.docker.com/compose/multiple-compose-files
# cf. https://docs.docker.com/compose/reference/#specifying-multiple-compose-files

# e.g. docker-compose -f docker-compose.base.yml -f docker-compose.dev.yml --progress=plain build
# e.g. docker compose -f docker-compose.base.yml -f docker-compose.dev.yml exec -u root php-fpm bash

services:
  php-fpm:
    volumes:
      # cf. https://docs.docker.com/desktop/previous-versions/edge-releases-mac/#docker-desktop-community-2330
      - type: bind
        source: ./backend
        target: ${CONTAINER_PROJECT_DIR}/backend
        consistency: delegated
      - type: volume
        source: node_modules-backend
        target: ${CONTAINER_PROJECT_DIR}/backend/node_modules/
    depends_on:
      redis:
        condition: service_healthy
        restart: true
  mysql:
    profiles: ["backend"]
    volumes:
      - type: bind
        source: ./backend/docker/mysql/create-testing-database.sh
        target: /docker-entrypoint-initdb.d/10-create-testing-database.sh
        read_only: true
  redis:
    profiles: ["backend"]
    image: redis:8.4-alpine
    ports:
      - ${FORWARD_REDIS_PORT:-6380}:6379
    volumes:
      - type: volume
        source: redis
        target: /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  # cf. https://github.com/axllent/mailpit
  mailpit:
    profiles: ["backend"]
    # cf. https://hub.docker.com/r/axllent/mailpit
    image: axllent/mailpit:latest
    ports:
      - ${FORWARD_MAILPIT_PORT:-1025}:1025
      - ${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025
volumes:
  redis:
    driver: local
  node_modules-backend:
    driver: local
