services:
  php-fpm:
    volumes:
      - type: volume
        source: vscode-extensions
        target: /home/${WEB_USER}/.vscode-server/extensions
      - type: bind
        source: ../
        target: ${DOCKER_PROJECT_DIR}
        consistency: delegated
volumes:
  vscode-extensions:
