# cf. https://laravel.com/docs/sail
# cf. https://docs.docker.com/compose/compose-file/#compose-file
# cf. https://docs.docker.com/compose/compose-file/build
services:
  laravel.test:
    build:
      # As relative path origin in `Dockerfile`
      # e.g. if it's `.`, `package.json` etc can be referenced as is,
      # but cannot if it's `./docker` etc. as parent path can't be reached.
      context: '.'
      dockerfile: ./docker/Dockerfile
      # cf. `Dockerfile.ARG`
      args:
        PHP_VERSION: '${PHP_VERSION}'
        WORKDIR: '${DOCKER_WORKDIR}'
        USERNAME: '${DOCKER_USERNAME}'
    # Used for built image name if `servive.build` is processed
    image: '${USER}/${COMPOSE_PROJECT_NAME}'
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      LC_ALL: 'C.UTF-8'
    # Starting directory in logining the container
    working_dir: '${DOCKER_WORKDIR}'
    volumes:
      - '.:${DOCKER_WORKDIR}'
      - 'vendor:${DOCKER_WORKDIR}/vendor'
      - 'node_modules:${DOCKER_WORKDIR}/node_modules'
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
  mysql:
    image: 'mariadb:10'
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mysql:/var/lib/mysql'
      - './docker/database/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6380}:6379'
    volumes:
      - 'redis:/data'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s
  # https://github.com/axllent/mailpit
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
volumes:
  vendor:
    driver: local
  node_modules:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local
