# For more information: https://laravel.com/docs/sail
# cf. https://docs.docker.com/compose/compose-file/#compose-file
# cf. https://docs.docker.com/compose/compose-file/build
services:
  laravel.test:
    build:
      # As relative path origin in `Dockerfile`
      # e.g. if it's `.`, `package.json` etc can be referenced as is,
      # but cannot if it's `./docker` etc. as parent path can't be reached.
      context: '.'
      dockerfile: ./docker/8.2-dev/Dockerfile
      # cf. `Dockerfile.ARG`
      args:
        WORKDIR: '${DOCKER_WORKDIR}'
        USERNAME: '${DOCKER_USERNAME}'
    # Ignored if `servive.build` exists
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      LC_ALL: 'C.UTF-8'
      LARAVEL_SAIL: 1
    # Starting directory in the container
    working_dir: '${DOCKER_WORKDIR}'
    volumes:
      - '.:${DOCKER_WORKDIR}'
      - 'vendor:${DOCKER_WORKDIR}/vendor'
      - 'node_modules:${DOCKER_WORKDIR}/node_modules'
    networks:
      - sail
    depends_on:
      - mysql
      - redis
  mysql:
    image: 'mariadb:10'
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './docker/database/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s
  # https://github.com/axllent/mailpit
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  vendor:
    driver: local
  node_modules:
    driver: local
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
