# cf. https://docs.docker.com/compose/compose-file
# cf. https://docs.docker.com/compose/multiple-compose-files
# cf. https://docs.docker.com/compose/reference/#specifying-multiple-compose-files

# e.g. docker-compose -f docker-compose.base.yml -f docker-compose.dev.yml --progress=plain build
# e.g. docker compose -f docker-compose.base.yml -f docker-compose.dev.yml exec -u root php-fpm bash

services:
  mysql:
    volumes:
      - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh:ro'
  redis:
    image: 'redis:7.2-alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6380}:6379'
    volumes:
      - 'redis:/data'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s
  # cf. https://github.com/axllent/mailpit
  mailpit:
    # cf. https://hub.docker.com/r/axllent/mailpit
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
volumes:
  redis:
    driver: local
