server {
  listen 80;
  listen [::]:80;

  server_name "${APP_DOMAIN}";

  location / {
    proxy_pass http://node:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # cf. https://nextjs.org/docs/pages/building-your-application/upgrading/version-12#hmr-connection-now-uses-a-websocket
  location /_next/webpack-hmr {
    proxy_pass "http://node:3000/_next/webpack-hmr";
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
