# cf. https://playwright.dev/docs/ci-intro
# cf. https://vercel.com/guides/how-can-i-run-end-to-end-tests-after-my-vercel-preview-deployment
#     https://docs.github.com/ja/webhooks-and-events/webhooks/webhook-events-and-payloads#deployment_status

name: Playwright Tests

on:
  deployment_status:

jobs:
  e2e:
    name: End-to-End Test
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      # cf. https://pnpm.io/continuous-integration#github-actions
      # cf. https://github.com/pnpm/action-setup
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: './frontend/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts --prefer-offline

      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps

      - name: Run tests
        run: pnpm test:e2e
        env:
          APP_URL: ${{ github.event.deployment_status.target_url }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
